export const SITE_NAME = "Čtyřlístkotéka" as const;
export const SITE_DESCRIPTION =
  "Soukromá sbírka čtyřlístků — nálezy, lokality a statistiky." as const;

// Image sizes (generated by sharp at sync time)
export const THUMB_SIZE = 400;
export const WEB_SIZE = 1600;
export const THUMB_QUALITY = 80;
export const WEB_QUALITY = 85;

// Paging / UI
export const FINDS_PER_PAGE = 48;
export const MAP_CLUSTER_RADIUS = 80;

// ISR revalidation (seconds)
export const HOME_REVALIDATE = 60 * 60; // 1 h
export const FIND_REVALIDATE = 24 * 60 * 60; // 24 h
export const STATS_REVALIDATE = 6 * 60 * 60; // 6 h

// Anonymization: rounding for public GPS (~100 m at midlatitudes)
export const ANON_GPS_PRECISION = 3;
