export const SITE_NAME = "Čtyřlístkotéka" as const;
export const SITE_DESCRIPTION =
  "Soukromá sbírka čtyřlístků — nálezy, lokality a statistiky." as const;

// Image sizes (generated by sharp at sync time)
export const THUMB_SIZE = 400;
export const WEB_SIZE = 1600;
export const THUMB_QUALITY = 80;
export const WEB_QUALITY = 85;

// Paging / UI
export const FINDS_PER_PAGE = 48;
export const MAP_CLUSTER_RADIUS = 80;

// ISR revalidation (seconds)
export const HOME_REVALIDATE = 60 * 60; // 1 h
export const FIND_REVALIDATE = 24 * 60 * 60; // 24 h
export const STATS_REVALIDATE = 6 * 60 * 60; // 6 h

// Anonymization: rounding for public GPS (~100 m at midlatitudes). Used by
// /mapa's raw-SQL coarsening pipeline; the find queries / detail page drop
// GPS entirely instead of coarsening (see src/lib/anonymize.ts).
export const ANON_GPS_PRECISION = 3;

/**
 * Find-detail page falls back to this location's first non-anonymized map
 * whenever the actual location info must be hidden — i.e. the find itself
 * is anonymized, so we mustn't reveal where it came from. The user's data
 * convention assigns location id 1 to a generic placeholder map.
 */
export const DEFAULT_LOCATION_ID = 1;

/**
 * The single location that historically holds ~80 % of the collection's
 * finds (and probably always will — it's the user's home patch with a
 * dense cluster of sub-maps). /sbirka exposes a one-click toggle to
 * exclude this location + all its descendants from the listing so the
 * "rest of the world" is browsable without paging through thousands
 * of rows from one place.
 *
 * Lives here, not inlined in the page, so updating it as the
 * collection grows is one constant change. The id matches
 * `LocationMap.id` = MAP_ID from the filename of the canonical map for
 * that location.
 */
export const DOMINANT_LOCATION_ID = 3;
