export const SITE_NAME = "Safronova čtyřlístkotéka" as const;
export const SITE_DESCRIPTION =
  "Soukromá sbírka čtyřlístků — nálezy, lokality a statistiky." as const;

// Image sizes (generated by sharp at sync time)
export const THUMB_SIZE = 400;
export const WEB_SIZE = 1600;
export const THUMB_QUALITY = 80;
export const WEB_QUALITY = 85;

// Paging / UI
export const FINDS_PER_PAGE = 48;
export const MAP_CLUSTER_RADIUS = 80;

/**
 * Radius (in metres) around a location's centre point that still counts
 * as "at the location" for finds at locations WITHOUT a polygon AOI.
 * Beyond this radius the find is treated as a deviation — coloured red
 * on the /sbirka rows and find-detail Lokalita section, and hidable as
 * a group via the "Skrýt odchýlené nálezy" toggle on /mapa.
 *
 * Locations WITH a polygon use `ST_Covers(polygon, coord)` instead;
 * the polygon already defines "at the location" without needing a
 * scalar radius. This constant only kicks in for the polygon-less
 * fallback.
 *
 * 5 m is deliberately strict — the centre point of a polygon-less
 * location is usually the exact spot the author wanted to anchor the
 * find to, not a vague neighbourhood, so even a few metres away reads
 * as a deviation.
 */
export const FIND_DEVIATION_RADIUS_M = 5;

/**
 * Stand-in area (m²) for locations that have no drawn polygon: the area of
 * the circle of {@link FIND_DEVIATION_RADIUS_M} radius around the map
 * centre (π·r² ≈ 78.5 m²). Lets us still surface an (estimated) area and
 * find density for polygon-less spots. Mirrors the `pi() * (5*5)` fallback
 * used in the /statistiky density ranking (src/lib/queries/stats.ts), so
 * the two surfaces agree. Always label values derived from it as estimates.
 */
export const POLYGON_FREE_AREA_M2 = Math.PI * FIND_DEVIATION_RADIUS_M ** 2;

// ISR revalidation (seconds)
export const HOME_REVALIDATE = 60 * 60; // 1 h
export const FIND_REVALIDATE = 24 * 60 * 60; // 24 h
export const STATS_REVALIDATE = 6 * 60 * 60; // 6 h

// Anonymization: rounding for public GPS (~100 m at midlatitudes). Used by
// /mapa's raw-SQL coarsening pipeline; the find queries / detail page drop
// GPS entirely instead of coarsening (see src/lib/anonymize.ts).
export const ANON_GPS_PRECISION = 3;

/**
 * Find-detail page falls back to this location's first non-anonymized map
 * whenever the actual location info must be hidden — i.e. the find itself
 * is anonymized, so we mustn't reveal where it came from. The user's data
 * convention assigns location id 1 to a generic placeholder map.
 */
export const DEFAULT_LOCATION_ID = 1;

/**
 * The single location that historically holds ~80 % of the collection's
 * finds (and probably always will — it's the user's home patch with a
 * dense cluster of sub-maps). /sbirka exposes a one-click toggle to
 * exclude this location + all its descendants from the listing so the
 * "rest of the world" is browsable without paging through thousands
 * of rows from one place.
 *
 * Lives here, not inlined in the page, so updating it as the
 * collection grows is one constant change. The id matches
 * `LocationMap.id` = MAP_ID from the filename of the canonical map for
 * that location.
 */
export const DOMINANT_LOCATION_ID = 3;

/**
 * The author's "home" location (map 00158). Two /mapa behaviours hang
 * off it: it's the default location the page centres + fits on a bare
 * visit (no ?focus / ?find deep link), and its centre point is drawn
 * with the author's Safronus logo instead of the usual blue dot — a
 * small personal easter egg. Both read this one constant so the home
 * spot moves in lockstep if the collection's centre of gravity shifts.
 * The id matches `LocationMap.id` = MAP_ID from the filename.
 */
export const AUTHOR_LOCATION_ID = 158;

/**
 * Historical "missing clovers" backfill window — the inclusive find-ID
 * range the user is gradually filling in (older finds that were never
 * scanned/uploaded). The home page's "Poslední nahrání chybějících
 * čtyřlístků" status reflects ONLY inserts whose id falls in this range;
 * finds below it are considered complete and finds above it are new
 * additions at the high end, not gap-fillers. Adjust as the gap closes.
 */
export const MISSING_CLOVER_ID_MIN = 667;
export const MISSING_CLOVER_ID_MAX = 13599;

/**
 * The "Czech record" find — the milestone of the largest four-leaf clover
 * collection in ČR. Used only as the default seed for the admin-assignable
 * special-find config (src/lib/specialFinds.*): on a fresh deploy with no
 * config file, this find gets the "record" effect. Once anything is edited
 * in /admin → Efekty, the config file becomes the source of truth.
 */
export const RECORD_FIND_ID = 20037;
