/**
 * One-shot deterministic shuffle of the clover-texts JSON. Runs once
 * before the texts are committed to the repo as
 * `src/data/clover-texts.shuffled.json`; the bundled output is then the
 * source of truth for the home-page rotator and is never re-shuffled.
 *
 * Usage:
 *   pnpm tsx scripts/shuffle-clover-texts.ts \
 *     --input ~/Downloads/ctyrlistek-texts.json \
 *     [--output src/data/clover-texts.shuffled.json] \
 *     [--seed ctyrlistkoteka-v1]
 *
 * Determinism comes from a seeded PRNG (mulberry32) keyed by a string
 * hash so re-running with the same seed reproduces the same order — a
 * collaborator regenerating the file should land on byte-identical
 * output. Only `meta` fields are touched: each `text` entry keeps its
 * original numeric `id` so the on-disk order is the *only* signal of
 * sequence. The original JSON is never modified.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

interface CloverText {
  id: number;
  category: string;
  title: string;
  text: string;
  source_type: "fact" | "lore" | "creative";
  /** Marks an entry as authored by the project owner — the home-page
   *  rotator renders these with a clover-themed paper variant and a
   *  BONUS badge. Optional; default `false`. */
  author?: boolean;
  /** Visible label override for author entries
   *  ("Báseň autora", "Rada autora", "Hláška autora", "Fakt autora",
   *  "Fakt o autorovi"). Ignored when `author` is falsy. */
  kind?: string;
}

interface CloverTextsFile {
  $schema?: string;
  meta?: Record<string, unknown>;
  texts: CloverText[];
}

function parseArgs(argv: ReadonlyArray<string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a && a.startsWith("--")) {
      const next = argv[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        out[a.slice(2)] = next;
        i++;
      } else {
        out[a.slice(2)] = "true";
      }
    }
  }
  return out;
}

/** Hash a UTF-8 string into a 32-bit unsigned int (cyrb53-lite). */
function seedFromString(s: string): number {
  let h1 = 0xdeadbeef ^ 0;
  let h2 = 0x41c6ce57 ^ 0;
  for (let i = 0; i < s.length; i++) {
    const ch = s.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h1 ^= Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  return h1 >>> 0;
}

/** Mulberry32 — small, fast, good-enough PRNG for shuffling 200 items. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle<T>(items: ReadonlyArray<T>, rng: () => number): T[] {
  const arr = items.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    const tmp = arr[i] as T;
    arr[i] = arr[j] as T;
    arr[j] = tmp;
  }
  return arr;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  // Default to the repo-tracked source so re-running the shuffle after
  // editing texts is a one-liner (`pnpm tsx scripts/shuffle-clover-texts.ts`).
  // The original Downloads JSON stays untouched as a backup; the canonical
  // editing target is `src/data/clover-texts.source.json`.
  const input =
    args.input ??
    resolve(__dirname, "..", "src", "data", "clover-texts.source.json");
  const output =
    args.output ??
    resolve(__dirname, "..", "src", "data", "clover-texts.shuffled.json");
  const seedString = args.seed ?? "ctyrlistkoteka-v1";

  const raw = readFileSync(resolve(input), "utf-8");
  const parsed = JSON.parse(raw) as CloverTextsFile;
  if (!Array.isArray(parsed.texts) || parsed.texts.length === 0) {
    console.error(`No texts found in ${input}`);
    process.exit(1);
  }

  const seed = seedFromString(seedString);
  const rng = mulberry32(seed);
  const shuffled = shuffle(parsed.texts, rng);

  const outPayload = {
    $generated:
      "Auto-generated by scripts/shuffle-clover-texts.ts. Do not edit by hand.",
    seed: seedString,
    sourceCount: parsed.texts.length,
    texts: shuffled,
  };

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, `${JSON.stringify(outPayload, null, 2)}\n`, "utf-8");
  console.log(
    `Shuffled ${shuffled.length} texts into ${output} (seed="${seedString}")`,
  );
}

main();
